from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED

root = Path('/Users/apple/Desktop/github.local/Li_Project/jiliang')
src = root / 'output/report/10_False_Localizing_Sign_文献计量分析报告_Medicine投稿修订版v4.docx'
out = root / 'output/report/10_False_Localizing_Sign_文献计量分析报告_Medicine投稿修订版v7.docx'
fig_net = root / 'input/info4/3840a974e6bc0c4a4a598a100149b5be.png'   # keyword co-occurrence network, 998x838
fig_clu = root / 'input/info4/55c24a14418a8c8c2defc0221e2266b8.jpg'   # LLR cluster map, 800x600

old_text = ('关键词网络显示影像学与鉴别诊断、颅内压相关表现、脑肿瘤/占位性病变、颈髓/脊髓压迫以及颅神经和运动体征等相互关联的主题。主题时间图按照关键词在本数据中的首次至最后一次出现年份绘制，红色区段反映记录覆盖时间，并非引文突现强度。')
new_text = ('The keyword co-occurrence network of deprescribing research in older adults contains 368 nodes and 802 links, '
            'with a network density of 0.0119 (Fig. B1). Keyword frequency reflects the level of research attention: the three most '
            'frequent keywords were older adults (n = 391), polypharmacy (n = 234), and people (n = 113). Keywords with betweenness '
            'centrality greater than 0.1 occupy hub positions in the co-occurrence network and represent research foci; these were '
            'general medicine (0.16) and screening tool (0.11). Among keywords with frequency >= 30 and betweenness centrality >= 0.05, '
            'the top three ranked by centrality were screening tool (0.11), outcome (0.10), and dementia (0.10). Based on these '
            'co-occurrence relationships, K-means clustering with log-likelihood ratio (LLR) labeling in CiteSpace identified 16 '
            'keyword clusters (#0-15; Fig. B2): #0 primary prevention, #1 potentially inappropriate medications, #2 systematic review, '
            '#3 end of life, #4 primary care, #5 medication management, #6 type 2 diabetes, #7 medication optimisation, '
            '#8 quality of life, #9 adverse events, #10 anticholinergic burden, #11 preferences, #12 strategy, #13 population, '
            '#14 association, and #15 nursing homes. The modularity (Q = 0.717 > 0.3) and weighted mean silhouette '
            '(S = 0.8647 > 0.5) indicate that the clusters are highly homogeneous and closely related, confirming that the '
            'clustering is convincing. The topic time map is drawn from the first to the last appearance year of each keyword '
            'in this dataset; red segments reflect record coverage time, not citation burst strength.')

old_cap = 'Fig. B1. Keyword co-occurrence network (A) and modularity-based clustered thematic structure (B). Synonymous variants were merged using a thesaurus file before analysis.'
new_cap = ('Fig. B1. Keyword co-occurrence network of deprescribing research in older adults (368 nodes, 802 links; '
           'network density = 0.0119). Node size is proportional to keyword frequency.')
new_cap2 = ('Fig. B2. Cluster map of keywords in deprescribing research generated by K-means clustering with log-likelihood '
            'ratio (LLR) labeling. Sixteen clusters (#0-15) were identified (modularity Q = 0.717, weighted mean silhouette S = 0.8647).')

# network png 998x838 at cx=5715000 -> cy=4798838
new_fig2_xml = (
    '<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:drawing>'
    '<wp:inline xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">'
    '<wp:extent cx="5715000" cy="4286250"/><wp:docPr id="29" name="Picture 29"/>'
    '<wp:cNvGraphicFramePr><a:graphicFrameLocks noChangeAspect="1"/></wp:cNvGraphicFramePr>'
    '<a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">'
    '<pic:pic><pic:nvPicPr><pic:cNvPr id="0" name="info4_keyword_cluster_map.jpg"/><pic:cNvPicPr/></pic:nvPicPr>'
    '<pic:blipFill><a:blip r:embed="rId36"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill>'
    '<pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="5715000" cy="4286250"/></a:xfrm>'
    '<a:prstGeom prst="rect"/></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline>'
    '</w:drawing></w:r></w:p>'
    '<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr>'
    '<w:rFonts w:ascii="Songti SC" w:hAnsi="Songti SC" w:eastAsia="Songti SC"/><w:i/><w:sz w:val="18"/></w:rPr>'
    '<w:t>' + new_cap2 + '</w:t></w:r></w:p>')

with ZipFile(src, 'r') as zin, ZipFile(out, 'w', ZIP_DEFLATED) as zout:
    for item in zin.infolist():
        data = zin.read(item.filename)
        if item.filename == 'word/media/image24.png':
            data = fig_net.read_bytes()
        elif item.filename == 'word/document.xml':
            doc = data.decode('utf-8')
            assert old_text in doc, 'body paragraph not found'
            assert old_cap in doc, 'caption not found'
            doc = doc.replace(old_text, new_text)
            doc = doc.replace(old_cap, new_cap)
            # keep aspect ratio of new network image (998x838) in Picture 26
            doc = doc.replace('<wp:extent cx="5715000" cy="3554197"/><wp:docPr id="26" name="Picture 26"/>',
                              '<wp:extent cx="5715000" cy="4798838"/><wp:docPr id="26" name="Picture 26"/>')
            doc = doc.replace('<a:ext cx="5715000" cy="3554197"/>', '<a:ext cx="5715000" cy="4798838"/>', 1)
            doc = doc.replace('name="fig10_keyword_network_and_clusters.png"',
                              'name="info4_keyword_cooccurrence_network.png"')
            # renumber following B figures first (B3 before B2 to avoid collision),
            # before the new Fig. B2 caption is inserted
            assert doc.count('Fig. B3.') == 1 and doc.count('Fig. B2.') == 1
            doc = doc.replace('Fig. B3.', 'Fig. B4.')
            doc = doc.replace('Fig. B2.', 'Fig. B3.')
            # insert cluster-map figure + caption right after the Fig. B1 caption paragraph
            anchor = '<w:t>' + new_cap + '</w:t></w:r></w:p>'
            assert anchor in doc, 'B1 caption anchor not found'
            doc = doc.replace(anchor, anchor + new_fig2_xml)
            data = doc.encode('utf-8')
        elif item.filename == 'word/_rels/document.xml.rels':
            rels = data.decode('utf-8')
            rel = ('<Relationship Id="rId36" '
                   'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" '
                   'Target="media/image36.jpg"/>')
            rels = rels.replace('</Relationships>', rel + '</Relationships>')
            data = rels.encode('utf-8')
        elif item.filename == '[Content_Types].xml':
            ct = data.decode('utf-8')
            if 'Extension="jpg"' not in ct:
                ct = ct.replace('<Default Extension="jpeg"',
                                '<Default Extension="jpg" ContentType="image/jpeg"/><Default Extension="jpeg"')
            data = ct.encode('utf-8')
        zout.writestr(item, data)
    zout.writestr('word/media/image36.jpg', fig_clu.read_bytes())
print(out)
